# Generated by Django 3.2 on 2021-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('orderplaced', 'orderplaced')], default='cart', max_length=120),
        ),
    ]
